name: 天翼云盘签到
on:
  workflow_dispatch:
  schedule:
    - cron: 30 2 * * *
jobs:
  sigin:
    name: 天翼云盘签到
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 14
    - uses: actions/checkout@v3
      with:
        repository: wes-lin/Cloud189Checkin
        ref: main
    - name: init
      run: |
        cd $GITHUB_WORKSPACE
        npm install
    - name: run
      uses: nick-fields/retry@v2
      env:
        TY_USER_NAME: ${{secrets.TY_USER_NAME}}
        TY_PASSWORD: ${{secrets.TY_PASSWORD}}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      with:
        timeout_minutes: 10
        max_attempts: 3
        command: |
          cd $GITHUB_WORKSPACE
          npm start
