name: 清理Workflow日志

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:
    inputs:
      days_old:
        description: "The amount of days old to delete"
        default: "7"
        required: false
      repository:
        description: "The repository to clean logs for (owner\\repo)"
        required: false

jobs:
  clean-logs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: igorjs/gh-actions-clean-workflow@main
        with:
          runs_older_than: ${{ github.event.inputs.days_old || '7' }}
          repo: ${{ github.event.inputs.repository || github.repository }}
          token: ${{ secrets.REPO_TOKEN || secrets.GITHUB_TOKEN }}
