name: 编译GitLens
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@main

      - name: Setup node
        uses: actions/setup-node@main
        with:
          node-version: latest

      - name: Setup pnpm
        uses: pnpm/action-setup@master
        with:
          version: 10

      - name: Build
        run: |
          set -e
          version=$(curl -L https://api.github.com/repos/gitkraken/vscode-gitlens/releases/latest | jq -r .tag_name)
          git clone --depth=1 -b $version https://github.com/gitkraken/vscode-gitlens.git source
          cd source
          rm -rf .git
          git apply ../patches/GitLens.patch
          pnpm install
          pnpm run package
          mv *.vsix ..

      - name: Upload files
        uses: actions/upload-artifact@main
        with:
          name: GitLens
          path: "*.vsix"
